version: '3'
services:
    nginx:
        build:
            context: ./
            args:
                NGINX_VERSION: '1.25.2'
                # https://hub.docker.com/_/nginx
        image: nginx-otavio
        container_name: nginx-otavio
        ports:
            - '80:80'
            - '443:443'
        # depends_on: 
        #     - server
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/letsencrypt:/etc/letsencrypt
            - ./nginx/renova-ssl.sh:/etc/nginx/renova-ssl.sh
            # - ./nginx/conf.d:/etc/nginx/conf.d
            # - ./public:/var/www/public
        networks:
            - net_local

    server:
        build:
            context: ./api/exemplo
        image: api
        container_name: server-otavio
        ports:
            - '3000:3000'
        # volumes:
        #     - ./public:/var/www/public
        networks:
            - net_local

networks:
    net_local:
        driver: bridge
