version: '3'
services:
    nginx:
        build:
            context: ./
            args:
                NGINX_VERSION: '1.25.2'
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
                AWS_KEY: ${AWS_KEY}
                AWS_SECRET_KEY: ${AWS_SECRET_KEY}
        env_file: ./.env
        image: nginx-otavio
        container_name: nginx-otavio
        ports:
            - '80:80'
            - '443:443'
        # depends_on: 
        #     - server
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
            - ./nginx/letsencrypt:/etc/letsencrypt
            - ./nginx/renova-ssl.sh:/etc/nginx/renova-ssl.sh
            # - ./public:/var/www/public
        networks:
            - net_local

    server:
        env_file: ./.env
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/conxpert-server:latest
        container_name: server-otavio
        ports:
            - '3000:3000'
        volumes:
            - ./nginx/renova-ssl.sh:/etc/nginx/renova-ssl.sh
        networks:
            - net_local

networks:
    net_local:
        driver: bridge
