---
- name: Criando template
  ansible.builtin.template:
    src: ../templates/versao.j2
    dest: ./.versao

- name: Lendo o arquivo de versão
  ansible.builtin.shell: "cat ./.versao"
  register: versao

- name: Verificando versão
  ansible.builtin.debug:
    msg: "{{ versao.stdout }}"

- name: Baixar image docker versão pré definida
  become: true
  community.docker.docker_image:
    name: "{{ versao.stdout }}" #"{{ aws_ecr_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/servidor:{{ image_tag }}"
    source: pull
  register: img_latest

- name: Verifica se existe um container rodando
  become: true
  community.docker.docker_container:
    name: server-otavio
    state: absent
    image: "{{ versao.stdout}}" #"{{ aws_ecr_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/servidor:{{ image_tag }}"
    command: sleep infinity
  register: docker

- name: Acessando pasta do projeto no servidor
  shell: cd ./nginx-ssl
# - name: Iniciando o novo container com nova imagem
#   become: true
#   community.docker.docker_container:
#     name: server-otavio
#     image: "{{ versao.stdout }}" #"{{ aws_ecr_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/servidor:{{ image_tag }}"
#     state: started
#     ports:
#       - "3000:3000"
