---
- name: Instalar as dependencias do Docker
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Adicionar o Docker GPG em apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Instalar o Docker
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

# - name: Adicionar usuario docker
#   become: true
#   ansible.builtin.user:
#     name: docker
#     state: present
#     group: sudo

# - name: Permissão do usuario docker
#   become: true
#   ansible.builtin.user:
#     name: docker
#     shell: /bin/bash
#     groups: sudo
#     append: yes

- name: Iniciando o serviço do docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
